import type { Task } from './types';
import { ROADMAP } from '@/entities/roadmap';

export const TASKS: Task[] = [
  {
    id: "osn-1-1",
    topicId: "osnovy",
    subtopicId: "st-osn-1",
    title: "Определение временной сложности",
    description: "Вам дана строка, описывающая паттерн алгоритма. Определите его временную сложность и верните строку с Big-O нотацией.\n\nПаттерны:\n- 'single_loop' — один цикл от 0 до n → O(n)\n- 'nested_loop' — два вложенных цикла от 0 до n → O(n^2)\n- 'binary_search' — деление массива пополам на каждом шаге → O(log n)\n- 'constant' — фиксированное количество операций → O(1)\n- 'triple_loop' — три вложенных цикла от 0 до n → O(n^3)\n\nПример:\nВход: 'single_loop'\nВыход: 'O(n)'",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-1-2",
    topicId: "osnovy",
    subtopicId: "st-osn-1",
    title: "Подсчёт операций во вложенных циклах",
    description: "Дано число n. Подсчитайте общее количество итераций для следующей конструкции вложенных циклов:\n\nfor i in range(n):\n    for j in range(i):\n        операция\n\nТо есть внутренний цикл выполняется 0 + 1 + 2 + ... + (n-1) раз.\n\nПример:\nВход: n = 5\nВыход: 10 (потому что 0 + 1 + 2 + 3 + 4 = 10)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-1-3",
    topicId: "osnovy",
    subtopicId: "st-osn-1",
    title: "Сравнение двух алгоритмов",
    description: "Даны два алгоритма:\n- Алгоритм A выполняет 5·n операций\n- Алгоритм B выполняет n² операций\n\nДано число n. Определите, какой алгоритм быстрее (выполняет меньше операций). Верните 'A', если алгоритм A быстрее, 'B', если алгоритм B быстрее, или 'equal', если количество операций одинаково.\n\nПример:\nВход: n = 10 → A: 50 операций, B: 100 операций → Ответ: 'A'\nВход: n = 3 → A: 15 операций, B: 9 операций → Ответ: 'B'\nВход: n = 5 → A: 25, B: 25 → Ответ: 'equal'",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-2-1",
    topicId: "osnovy",
    subtopicId: "st-osn-2",
    title: "Переворот массива",
    description: "Дан массив элементов. Верните новый массив, в котором элементы расположены в обратном порядке.\n\nПример:\nВход: [1, 2, 3, 4, 5]\nВыход: [5, 4, 3, 2, 1]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-2-2",
    topicId: "osnovy",
    subtopicId: "st-osn-2",
    title: "Проверка палиндрома",
    description: "Дана строка. Определите, является ли она палиндромом (читается одинаково слева направо и справа налево).\n\nПример:\nВход: 'abcba' → True\nВход: 'hello' → False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-2-3",
    topicId: "osnovy",
    subtopicId: "st-osn-2",
    title: "Два числа с заданной суммой (Two Sum)",
    description: "Дан массив целых чисел nums и целевое число target. Найдите два элемента, сумма которых равна target, и верните их индексы в виде списка.\n\nГарантируется, что решение существует и оно единственное.\n\nПример:\nВход: nums = [2, 7, 11, 15], target = 9\nВыход: [0, 1] (потому что nums[0] + nums[1] = 2 + 7 = 9)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-2-4",
    topicId: "osnovy",
    subtopicId: "st-osn-2",
    title: "Циклический сдвиг массива",
    description: "Дан массив nums и число k. Выполните циклический сдвиг массива вправо на k позиций. Элементы, выходящие за правый край, переносятся в начало.\n\nПример:\nВход: nums = [1, 2, 3, 4, 5], k = 2\nВыход: [4, 5, 1, 2, 3]\n\nВход: nums = [1, 2, 3], k = 1\nВыход: [3, 1, 2]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-2-5",
    topicId: "osnovy",
    subtopicId: "st-osn-2",
    title: "Наибольшая подстрока без повторяющихся символов",
    description: "Дана строка s. Найдите длину наибольшей подстроки, которая не содержит повторяющихся символов.\n\nПример:\nВход: 'abcabcbb' → 3 (подстрока 'abc')\nВход: 'bbbbb' → 1 (подстрока 'b')\nВход: 'pwwkew' → 3 (подстрока 'wke')",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-3-1",
    topicId: "osnovy",
    subtopicId: "st-osn-3",
    title: "Поиск максимального элемента",
    description: "Дан массив целых чисел. Найдите и верните максимальный элемент массива.\n\nПример:\nВход: [1, 5, 3, 9, 2]\nВыход: 9",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-3-2",
    topicId: "osnovy",
    subtopicId: "st-osn-3",
    title: "Удаление дубликатов из отсортированного массива",
    description: "Дан отсортированный массив целых чисел. Верните новый массив, в котором каждый элемент встречается только один раз.\n\nПример:\nВход: [1, 1, 2, 2, 3]\nВыход: [1, 2, 3]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-3-3",
    topicId: "osnovy",
    subtopicId: "st-osn-3",
    title: "Слияние двух отсортированных массивов",
    description: "Даны два отсортированных массива. Объедините их в один отсортированный массив.\n\nПример:\nВход: arr1 = [1, 3, 5], arr2 = [2, 4, 6]\nВыход: [1, 2, 3, 4, 5, 6]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-3-4",
    topicId: "osnovy",
    subtopicId: "st-osn-3",
    title: "Поиск пропущенного числа",
    description: "Дан массив, содержащий n-1 различных чисел из диапазона от 1 до n. Одно число из этого диапазона отсутствует. Найдите его.\n\nПример:\nВход: [1, 2, 4, 5] → пропущено число 3 (диапазон 1..5)\nВход: [2, 3, 4, 5] → пропущено число 1 (диапазон 1..5)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-4-1",
    topicId: "osnovy",
    subtopicId: "st-osn-4",
    title: "Частота элементов",
    description: "Дан массив элементов. Посчитайте, сколько раз каждый элемент встречается в массиве, и верните словарь (dict), где ключ — элемент, значение — количество его вхождений.\n\nПример:\nВход: [1, 2, 2, 3, 3, 3]\nВыход: {1: 1, 2: 2, 3: 3}",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-4-2",
    topicId: "osnovy",
    subtopicId: "st-osn-4",
    title: "Проверка анаграмм",
    description: "Даны две строки. Определите, являются ли они анаграммами друг друга (содержат одни и те же символы в одинаковом количестве).\n\nПример:\nВход: s1 = 'listen', s2 = 'silent' → True\nВход: s1 = 'hello', s2 = 'world' → False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-4-3",
    topicId: "osnovy",
    subtopicId: "st-osn-4",
    title: "Первый неповторяющийся символ",
    description: "Дана строка. Найдите индекс первого символа, который встречается в строке ровно один раз. Если такого символа нет, верните -1.\n\nПример:\nВход: 'leetcode' → 0 (символ 'l' встречается один раз)\nВход: 'aabb' → -1 (все символы повторяются)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-4-4",
    topicId: "osnovy",
    subtopicId: "st-osn-4",
    title: "Группировка анаграмм",
    description: "Дан массив строк. Сгруппируйте строки, являющиеся анаграммами друг друга. Верните отсортированный список групп (каждая группа тоже отсортирована).\n\nПример:\nВход: ['eat', 'tea', 'tan', 'ate', 'nat', 'bat']\nВыход: [['ate', 'eat', 'tea'], ['bat'], ['nat', 'tan']]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-4-5",
    topicId: "osnovy",
    subtopicId: "st-osn-4",
    title: "Наибольшая последовательная цепочка",
    description: "Дан несортированный массив целых чисел. Найдите длину наибольшей последовательности подряд идущих чисел (порядок в массиве не важен).\n\nПример:\nВход: [100, 4, 200, 1, 3, 2] → 4 (последовательность: 1, 2, 3, 4)\nВход: [0, 3, 7, 2, 5, 8, 4, 6, 0, 1] → 9 (последовательность: 0–8)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-5-1",
    topicId: "osnovy",
    subtopicId: "st-osn-5",
    title: "Проверка скобок",
    description: "Дана строка, содержащая только символы '(', ')', '{', '}', '[', ']'. Определите, является ли строка валидной: каждая открывающая скобка должна иметь соответствующую закрывающую скобку того же типа, и скобки должны закрываться в правильном порядке.\n\nПример:\nВход: '()[]{}' → True\nВход: '(]' → False\nВход: '([)]' → False\nВход: '{[]}' → True",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-5-2",
    topicId: "osnovy",
    subtopicId: "st-osn-5",
    title: "Очередь на двух стеках",
    description: "Реализуйте очередь (FIFO), используя принцип двух стеков. Дан список команд: положительное число означает 'добавить в очередь', а 0 означает 'извлечь из очереди'. Верните список всех извлечённых значений.\n\nПринцип: один стек для добавления, второй — для извлечения. Когда стек извлечения пуст, перекладываем все элементы из стека добавления.\n\nПример:\nВход: [1, 2, 3, 0, 0, 0]\nВыход: [1, 2, 3] (добавили 1, 2, 3, затем извлекли в порядке очереди)",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-5-3",
    topicId: "osnovy",
    subtopicId: "st-osn-5",
    title: "Стек с минимумом (Min Stack)",
    description: "Реализуйте стек, который поддерживает получение минимального элемента за O(1). Дан список строковых команд:\n- 'push X' — положить число X в стек\n- 'pop' — извлечь верхний элемент\n- 'min' — получить текущий минимум\n\nВерните список результатов всех операций 'min'.\n\nПример:\nВход: ['push 3', 'push 5', 'min', 'push 2', 'min', 'pop', 'min']\nВыход: [3, 2, 3]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-5-4",
    topicId: "osnovy",
    subtopicId: "st-osn-5",
    title: "Обратная польская нотация",
    description: "Дан массив строк tokens, представляющий арифметическое выражение в обратной польской нотации (постфиксной). Вычислите значение выражения.\n\nДопустимые операторы: +, -, *, /. Деление — целочисленное (округление к нулю).\n\nПример:\nВход: ['2', '1', '+', '3', '*'] → ((2 + 1) * 3) = 9\nВход: ['4', '13', '5', '/', '+'] → (4 + (13 / 5)) = 6",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "osn-5-5",
    topicId: "osnovy",
    subtopicId: "st-osn-5",
    title: "Наибольший прямоугольник в гистограмме",
    description: "Дан массив целых чисел heights, где heights[i] — высота столбца гистограммы шириной 1. Найдите площадь наибольшего прямоугольника, который можно вписать в гистограмму.\n\nПример:\nВход: [2, 1, 5, 6, 2, 3] → 10 (прямоугольник высотой 5 и шириной 2 на позициях 2-3)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-1-1",
    topicId: "rekursiya",
    subtopicId: "st-rek-1",
    title: "Факториал числа",
    description: "Вычислите факториал числа n рекурсивно. Факториал n (обозначается n!) — это произведение всех натуральных чисел от 1 до n.\n\nБазовые случаи: 0! = 1, 1! = 1\n\nПример:\nВход: 5 → 5! = 5 × 4 × 3 × 2 × 1 = 120",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-1-2",
    topicId: "rekursiya",
    subtopicId: "st-rek-1",
    title: "Сумма цифр числа",
    description: "Найдите сумму всех цифр числа n рекурсивно.\n\nПример:\nВход: 123 → 1 + 2 + 3 = 6\nВход: 999 → 9 + 9 + 9 = 27",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-1-3",
    topicId: "rekursiya",
    subtopicId: "st-rek-1",
    title: "Возведение в степень",
    description: "Реализуйте функцию возведения числа x в степень n рекурсивно. Используйте метод быстрого возведения в степень:\n- x^0 = 1\n- Если n чётное: x^n = (x^(n/2))²\n- Если n нечётное: x^n = x · x^(n-1)\n- Если n отрицательное: x^n = 1 / x^(-n)\n\nПример:\nВход: x = 2, n = 10 → 1024\nВход: x = 2, n = -2 → 0.25",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-1-4",
    topicId: "rekursiya",
    subtopicId: "st-rek-1",
    title: "Все перестановки массива",
    description: "Дан массив уникальных чисел. Сгенерируйте все возможные перестановки элементов массива.\n\nПример:\nВход: [1, 2, 3]\nВыход: [[1, 2, 3], [1, 3, 2], [2, 1, 3], [2, 3, 1], [3, 1, 2], [3, 2, 1]]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-2-1",
    topicId: "rekursiya",
    subtopicId: "st-rek-2",
    title: "Числа Фибоначчи",
    description: "Вычислите n-е число Фибоначчи рекурсивно.\n\nПоследовательность Фибоначчи: 0, 1, 1, 2, 3, 5, 8, 13, 21, 34, 55, ...\n- F(0) = 0\n- F(1) = 1\n- F(n) = F(n-1) + F(n-2) для n ≥ 2\n\nПример:\nВход: 5 → 5\nВход: 10 → 55",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-2-2",
    topicId: "rekursiya",
    subtopicId: "st-rek-2",
    title: "Числа Трибоначчи",
    description: "Вычислите n-е число Трибоначчи.\n\nПоследовательность Трибоначчи: 0, 1, 1, 2, 4, 7, 13, 24, 44, 81, 149, ...\n- T(0) = 0\n- T(1) = 1\n- T(2) = 1\n- T(n) = T(n-1) + T(n-2) + T(n-3) для n ≥ 3\n\nПример:\nВход: 4 → 4\nВход: 10 → 149",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-2-3",
    topicId: "rekursiya",
    subtopicId: "st-rek-2",
    title: "Подъём по лестнице",
    description: "Вы стоите у подножия лестницы из n ступенек. За один шаг вы можете подняться на 1, 2 или 3 ступеньки. Сколько различных способов добраться до вершины?\n\nПример:\nВход: 3 → 4 способа:\n  1. 1+1+1\n  2. 1+2\n  3. 2+1\n  4. 3\n\nВход: 4 → 7 способов",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-3-1",
    topicId: "rekursiya",
    subtopicId: "st-rek-3",
    title: "Итеративный факториал",
    description: "Концепция хвостовой рекурсии: вместо накопления стека вызовов результат передаётся как аргумент. Такую рекурсию легко преобразовать в цикл.\n\nПреобразуйте рекурсивный факториал в итеративный. Вместо:\n  factorial(n) = n * factorial(n-1)\nИспользуйте цикл с аккумулятором.\n\nПример:\nВход: 5 → 120\nВход: 0 → 1",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-3-2",
    topicId: "rekursiya",
    subtopicId: "st-rek-3",
    title: "Итеративное число Фибоначчи",
    description: "Преобразуйте рекурсивное вычисление чисел Фибоначчи в итеративное. Хвостовая рекурсия для Фибоначчи передаёт два аккумулятора (текущее и предыдущее значения), что легко преобразуется в цикл.\n\nВместо двойной рекурсии F(n) = F(n-1) + F(n-2) используйте две переменные и цикл.\n\nПример:\nВход: 10 → 55\nВход: 30 → 832040",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-4-1",
    topicId: "rekursiya",
    subtopicId: "st-rek-4",
    title: "Бинарный поиск (рекурсивный)",
    description: "Реализуйте бинарный поиск рекурсивно. Дан отсортированный массив и целевое значение. Верните индекс элемента или -1, если он не найден.\n\nАлгоритм: сравниваем средний элемент с целевым. Если равны — нашли. Если цель больше — ищем в правой половине. Если меньше — в левой.\n\nПример:\nВход: arr = [1, 3, 5, 7, 9], target = 5 → 2\nВход: arr = [1, 3, 5, 7, 9], target = 4 → -1",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-4-2",
    topicId: "rekursiya",
    subtopicId: "st-rek-4",
    title: "Сортировка слиянием (Merge Sort)",
    description: "Реализуйте сортировку слиянием — классический алгоритм «разделяй и властвуй».\n\nАлгоритм:\n1. Разделите массив пополам\n2. Рекурсивно отсортируйте каждую половину\n3. Слейте две отсортированные половины в один массив\n\nПример:\nВход: [5, 3, 8, 1, 2]\nВыход: [1, 2, 3, 5, 8]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "rek-4-3",
    topicId: "rekursiya",
    subtopicId: "st-rek-4",
    title: "Подсчёт инверсий в массиве",
    description: "Дан массив чисел. Инверсия — это пара индексов (i, j), где i < j, но arr[i] > arr[j]. Подсчитайте общее количество инверсий.\n\nИспользуйте модификацию сортировки слиянием для эффективного подсчёта за O(n log n).\n\nПример:\nВход: [2, 4, 1, 3, 5] → 3 инверсии: (2,1), (4,1), (4,3)\nВход: [3, 2, 1] → 3 инверсии: (3,2), (3,1), (2,1)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-bubble",
    topicId: "sortirovki",
    subtopicId: "st-sort-1",
    title: "Сортировка пузырьком",
    description: "Реализуйте сортировку пузырьком. Алгоритм последовательно сравнивает соседние элементы и меняет их местами, если они стоят в неправильном порядке.\n\nПример:\nВход: [5, 3, 8, 4, 2]\nВыход: [2, 3, 4, 5, 8]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-selection",
    topicId: "sortirovki",
    subtopicId: "st-sort-1",
    title: "Сортировка выбором",
    description: "Реализуйте сортировку выбором. На каждом шаге алгоритм находит минимальный элемент в неотсортированной части массива и ставит его на правильную позицию.\n\nПример:\nВход: [64, 25, 12, 22, 11]\nВыход: [11, 12, 22, 25, 64]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-insertion-swaps",
    topicId: "sortirovki",
    subtopicId: "st-sort-1",
    title: "Сортировка вставками: подсчёт обменов",
    description: "Реализуйте сортировку вставками и верните количество обменов (swap), выполненных в процессе сортировки. Обмен — это перестановка двух соседних элементов.\n\nПример:\nВход: [3, 1, 2]\nВыход: 2\nПояснение: [3,1,2] → swap(3,1) → [1,3,2] → swap(3,2) → [1,2,3]. Всего 2 обмена.",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-min-swaps",
    topicId: "sortirovki",
    subtopicId: "st-sort-1",
    title: "Минимальное количество обменов для сортировки",
    description: "Дан массив из различных целых чисел. Найдите минимальное количество обменов (swap любых двух элементов), необходимых для сортировки массива по возрастанию.\n\nПример:\nВход: [4, 3, 2, 1]\nВыход: 2\nПояснение: swap(4,1) → [1,3,2,4], swap(3,2) → [1,2,3,4].",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-partition",
    topicId: "sortirovki",
    subtopicId: "st-sort-2",
    title: "Разделение массива относительно опорного элемента",
    description: "Дан массив и опорный элемент (pivot). Разделите массив на три части: элементы меньше pivot, равные pivot, больше pivot. Верните результирующий массив.\n\nПример:\nВход: arr = [3, 5, 2, 8, 1, 4], pivot = 4\nВыход: [3, 2, 1, 4, 5, 8]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-quicksort",
    topicId: "sortirovki",
    subtopicId: "st-sort-2",
    title: "Быстрая сортировка (Quicksort)",
    description: "Реализуйте алгоритм быстрой сортировки. Выберите опорный элемент, разделите массив на части меньше и больше опорного, рекурсивно отсортируйте каждую часть.\n\nПример:\nВход: [10, 7, 8, 9, 1, 5]\nВыход: [1, 5, 7, 8, 9, 10]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-kth-smallest",
    topicId: "sortirovki",
    subtopicId: "st-sort-2",
    title: "K-й наименьший элемент (Quickselect)",
    description: "Найдите k-й наименьший элемент массива (нумерация с 1), используя алгоритм Quickselect. Не сортируйте весь массив.\n\nПример:\nВход: arr = [3, 1, 2, 5, 4], k = 3\nВыход: 3\nПояснение: Отсортированный массив [1,2,3,4,5], третий элемент — 3.",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-merge-arrays",
    topicId: "sortirovki",
    subtopicId: "st-sort-3",
    title: "Слияние двух отсортированных массивов",
    description: "Даны два отсортированных массива. Объедините их в один отсортированный массив.\n\nПример:\nВход: a = [1, 3, 5], b = [2, 4, 6]\nВыход: [1, 2, 3, 4, 5, 6]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-mergesort",
    topicId: "sortirovki",
    subtopicId: "st-sort-3",
    title: "Сортировка слиянием (Merge Sort)",
    description: "Реализуйте сортировку слиянием. Разделите массив пополам, рекурсивно отсортируйте каждую половину и слейте результаты.\n\nПример:\nВход: [38, 27, 43, 3, 9, 82, 10]\nВыход: [3, 9, 10, 27, 38, 43, 82]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-count-inversions",
    topicId: "sortirovki",
    subtopicId: "st-sort-3",
    title: "Подсчёт инверсий (Merge Sort)",
    description: "Инверсия — пара индексов (i, j), где i < j, но arr[i] > arr[j]. Подсчитайте общее количество инверсий в массиве, используя модифицированную сортировку слиянием.\n\nПример:\nВход: [2, 4, 1, 3, 5]\nВыход: 3\nПояснение: Инверсии: (2,1), (4,1), (4,3).",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-check-heap",
    topicId: "sortirovki",
    subtopicId: "st-sort-4",
    title: "Проверка на мин-кучу",
    description: "Дан массив, представляющий бинарное дерево (индекс 0 — корень, дети узла i имеют индексы 2i+1 и 2i+2). Проверьте, является ли массив корректной мин-кучей (каждый родитель ≤ своих детей).\n\nПример:\nВход: [1, 2, 3, 4, 5]\nВыход: True\n\nВход: [2, 1, 3]\nВыход: False (2 > 1, родитель больше ребёнка)",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-k-largest",
    topicId: "sortirovki",
    subtopicId: "st-sort-4",
    title: "K наибольших элементов",
    description: "Дан массив целых чисел и число k. Найдите k наибольших элементов массива. Верните их в порядке возрастания.\n\nПример:\nВход: arr = [3, 1, 5, 2, 4], k = 3\nВыход: [3, 4, 5]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-merge-k-lists",
    topicId: "sortirovki",
    subtopicId: "st-sort-4",
    title: "Слияние K отсортированных списков",
    description: "Дан список из k отсортированных списков. Объедините все списки в один отсортированный список.\n\nПример:\nВход: [[1, 4, 5], [1, 3, 4], [2, 6]]\nВыход: [1, 1, 2, 3, 4, 4, 5, 6]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-counting",
    topicId: "sortirovki",
    subtopicId: "st-sort-5",
    title: "Сортировка подсчётом",
    description: "Реализуйте сортировку подсчётом для массива неотрицательных целых чисел. Алгоритм считает количество вхождений каждого значения и восстанавливает отсортированный массив.\n\nПример:\nВход: [4, 2, 2, 8, 3, 3, 1]\nВыход: [1, 2, 2, 3, 3, 4, 8]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-by-frequency",
    topicId: "sortirovki",
    subtopicId: "st-sort-5",
    title: "Сортировка по частоте",
    description: "Отсортируйте массив по убыванию частоты элементов. Элементы с одинаковой частотой расположите в порядке возрастания значения.\n\nПример:\nВход: [2, 3, 1, 3, 2]\nВыход: [2, 2, 3, 3, 1]\nПояснение: 2 и 3 встречаются по 2 раза (выводим 2 перед 3), затем 1 один раз.",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "sort-radix",
    topicId: "sortirovki",
    subtopicId: "st-sort-5",
    title: "Поразрядная сортировка (Radix Sort)",
    description: "Реализуйте поразрядную сортировку для массива неотрицательных целых чисел. Алгоритм сортирует числа поразрядно — от младшего разряда к старшему, используя устойчивую сортировку на каждом шаге.\n\nПример:\nВход: [170, 45, 75, 90, 802, 24, 2, 66]\nВыход: [2, 24, 45, 66, 75, 90, 170, 802]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-linear",
    topicId: "poisk",
    subtopicId: "st-pois-1",
    title: "Линейный поиск элемента",
    description: "Найдите индекс первого вхождения целевого элемента в неотсортированном массиве. Если элемент не найден, верните -1.\n\nПример:\nВход: arr = [4, 2, 7, 1, 9], target = 7\nВыход: 2",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-all-indices",
    topicId: "poisk",
    subtopicId: "st-pois-1",
    title: "Все индексы вхождений элемента",
    description: "Найдите все индексы вхождений целевого элемента в массиве. Верните список индексов в порядке возрастания.\n\nПример:\nВход: arr = [1, 2, 3, 2, 1], target = 2\nВыход: [1, 3]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-majority",
    topicId: "poisk",
    subtopicId: "st-pois-1",
    title: "Мажоритарный элемент",
    description: "Найдите мажоритарный элемент массива — элемент, который встречается более чем n/2 раз, где n — длина массива. Если такого элемента нет, верните -1.\n\nПример:\nВход: [3, 2, 3]\nВыход: 3\nПояснение: 3 встречается 2 раза из 3 (2 > 3/2).\n\nВход: [1, 2, 3]\nВыход: -1",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-binary",
    topicId: "poisk",
    subtopicId: "st-pois-2",
    title: "Бинарный поиск",
    description: "Реализуйте бинарный поиск в отсортированном массиве. Верните индекс целевого элемента или -1, если элемент не найден.\n\nПример:\nВход: arr = [1, 3, 5, 7, 9], target = 5\nВыход: 2",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-first-last",
    topicId: "poisk",
    subtopicId: "st-pois-2",
    title: "Первая и последняя позиция элемента",
    description: "В отсортированном массиве найдите индексы первого и последнего вхождения целевого элемента. Если элемент не найден, верните [-1, -1].\n\nПример:\nВход: arr = [5, 7, 7, 8, 8, 10], target = 8\nВыход: [3, 4]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-rotated",
    topicId: "poisk",
    subtopicId: "st-pois-2",
    title: "Поиск в развёрнутом отсортированном массиве",
    description: "Отсортированный массив был развёрнут в некоторой точке (например, [4,5,6,7,0,1,2] — это развёрнутый [0,1,2,4,5,6,7]). Найдите индекс целевого элемента за O(log n) или верните -1.\n\nПример:\nВход: arr = [4, 5, 6, 7, 0, 1, 2], target = 0\nВыход: 4",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-median-arrays",
    topicId: "poisk",
    subtopicId: "st-pois-2",
    title: "Медиана двух отсортированных массивов",
    description: "Даны два отсортированных массива nums1 и nums2. Найдите медиану объединённого массива за O(log(min(m,n))).\n\nПример:\nВход: nums1 = [1, 3], nums2 = [2]\nВыход: 2\n\nВход: nums1 = [1, 2], nums2 = [3, 4]\nВыход: 2.5",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-sqrt",
    topicId: "poisk",
    subtopicId: "st-pois-3",
    title: "Целочисленный квадратный корень",
    description: "Вычислите целочисленный квадратный корень числа n (округлённый вниз). Используйте бинарный поиск.\n\nПример:\nВход: 8\nВыход: 2\nПояснение: √8 ≈ 2.83, округляем вниз до 2.\n\nВход: 16\nВыход: 4",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-ship-packages",
    topicId: "poisk",
    subtopicId: "st-pois-3",
    title: "Минимальная грузоподъёмность для доставки",
    description: "Конвейер выдаёт посылки весом weights[i]. Нужно доставить все посылки за D дней в порядке очереди. Каждый день грузится столько последовательных посылок, сколько влезает. Найдите минимальную грузоподъёмность корабля.\n\nПример:\nВход: weights = [1,2,3,4,5,6,7,8,9,10], days = 5\nВыход: 15\nПояснение: [1,2,3,4,5], [6,7], [8], [9], [10] — 5 дней при грузоподъёмности 15.",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-split-array",
    topicId: "poisk",
    subtopicId: "st-pois-3",
    title: "Разделение массива на K частей с минимальной максимальной суммой",
    description: "Разделите массив на K непустых непрерывных подмассивов так, чтобы максимальная сумма подмассива была минимальной. Верните эту минимальную максимальную сумму.\n\nПример:\nВход: arr = [7, 2, 5, 10, 8], k = 2\nВыход: 18\nПояснение: [7,2,5] (сумма 14) и [10,8] (сумма 18). Максимум = 18, и это минимально возможный.",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-count-range",
    topicId: "poisk",
    subtopicId: "st-pois-4",
    title: "Количество элементов в диапазоне [a, b]",
    description: "Дан отсортированный массив. Подсчитайте количество элементов, попадающих в диапазон [a, b] (включительно). Используйте бинарный поиск (bisect).\n\nПример:\nВход: arr = [1, 2, 3, 4, 5, 6], a = 2, b = 5\nВыход: 4\nПояснение: Элементы 2, 3, 4, 5 попадают в диапазон.",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-closest",
    topicId: "poisk",
    subtopicId: "st-pois-4",
    title: "Ближайшее значение в отсортированном массиве",
    description: "Дан отсортированный массив. Найдите элемент, ближайший к заданному значению target. При равных расстояниях верните меньший элемент.\n\nПример:\nВход: arr = [1, 3, 8, 10, 15], target = 12\nВыход: 10\nПояснение: |10-12| = 2 < |15-12| = 3, ближайший — 10.",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "search-count-smaller",
    topicId: "poisk",
    subtopicId: "st-pois-4",
    title: "Количество меньших элементов для каждого элемента",
    description: "Для каждого элемента массива посчитайте, сколько элементов во всём массиве строго меньше него. Верните массив с ответами.\n\nПример:\nВход: [5, 2, 6, 1]\nВыход: [2, 1, 3, 0]\nПояснение: Меньше 5 — два элемента (2 и 1), меньше 2 — один (1), меньше 6 — три (5, 2, 1), меньше 1 — ноль.",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-basic-1",
    topicId: "derevya",
    subtopicId: "st-der-1",
    title: "Максимальная глубина бинарного дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Найдите его максимальную глубину — количество узлов на самом длинном пути от корня до листа.\n\nПример:\nВход: [3, 9, 20, None, None, 15, 7]\nДерево:\n    3\n   / \\\n  9  20\n     / \\\n    15   7\nВыход: 3",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-basic-2",
    topicId: "derevya",
    subtopicId: "st-der-1",
    title: "Проверка симметричности бинарного дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Проверьте, является ли оно симметричным (зеркальным относительно центра).\n\nПример:\nВход: [1, 2, 2, 3, 4, 4, 3]\nДерево:\n      1\n     / \\\n    2   2\n   / \\ / \\\n  3  4 4  3\nВыход: True",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-basic-3",
    topicId: "derevya",
    subtopicId: "st-der-1",
    title: "Построить BST из отсортированного массива",
    description: "Дан отсортированный массив целых чисел. Постройте из него сбалансированное бинарное дерево поиска (BST) и верните его в виде списка (level-order).\n\nПример:\nВход: [-10, -3, 0, 5, 9]\nВыход: [0, -10, 5, None, -3, None, 9]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bfs-1",
    topicId: "derevya",
    subtopicId: "st-der-2",
    title: "Обход дерева по уровням",
    description: "Дано бинарное дерево в виде списка (level-order). Выполните обход по уровням и верните список списков, где каждый внутренний список содержит значения узлов одного уровня.\n\nПример:\nВход: [3, 9, 20, None, None, 15, 7]\nВыход: [[3], [9, 20], [15, 7]]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bfs-2",
    topicId: "derevya",
    subtopicId: "st-der-2",
    title: "Вид дерева справа",
    description: "Дано бинарное дерево в виде списка (level-order). Верните список значений узлов, видимых при взгляде на дерево справа (последний узел каждого уровня).\n\nПример:\nВход: [1, 2, 3, None, 5, None, 4]\nДерево:\n    1\n   / \\\n  2   3\n   \\   \\\n    5   4\nВыход: [1, 3, 4]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bfs-3",
    topicId: "derevya",
    subtopicId: "st-der-2",
    title: "Минимальная глубина бинарного дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Найдите минимальную глубину — длину кратчайшего пути от корня до ближайшего листа.\n\nПример:\nВход: [3, 9, 20, None, None, 15, 7]\nВыход: 2 (путь 3 → 9)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-dfs-1",
    topicId: "derevya",
    subtopicId: "st-der-3",
    title: "Симметричный (inorder) обход дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Выполните симметричный (inorder) обход и верните список значений.\n\nПорядок: левое поддерево → корень → правое поддерево.\n\nПример:\nВход: [1, None, 2, 3]\nДерево:\n  1\n   \\\n    2\n   /\n  3\nВыход: [1, 3, 2]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-dfs-2",
    topicId: "derevya",
    subtopicId: "st-der-3",
    title: "Сумма пути от корня до листа",
    description: "Дано бинарное дерево и целевая сумма. Определите, существует ли путь от корня до листа, сумма значений которого равна target.\n\nПример:\nВход: tree=[5, 4, 8, 11, None, 13, 4, 7, 2, None, None, None, 1], target=22\nПуть: 5 → 4 → 11 → 2 = 22\nВыход: True",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-dfs-3",
    topicId: "derevya",
    subtopicId: "st-der-3",
    title: "Все пути с заданной суммой",
    description: "Дано бинарное дерево и целевая сумма. Найдите все пути от корня до листа, сумма значений которых равна target.\n\nПример:\nВход: tree=[5, 4, 8, 11, None, 13, 4, 7, 2, None, None, 5, 1], target=22\nВыход: [[5, 4, 11, 2], [5, 8, 4, 5]]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bst-1",
    topicId: "derevya",
    subtopicId: "st-der-4",
    title: "Проверка BST",
    description: "Дано бинарное дерево в виде списка (level-order). Определите, является ли оно корректным бинарным деревом поиска (BST).\n\nВ BST для каждого узла: все значения в левом поддереве строго меньше, все в правом — строго больше.\n\nПример:\nВход: [2, 1, 3] → True\nВход: [5, 1, 4, None, None, 3, 6] → False (4 < 5 в правом поддереве)",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bst-2",
    topicId: "derevya",
    subtopicId: "st-der-4",
    title: "K-й наименьший элемент в BST",
    description: "Дано BST в виде списка и число k. Найдите k-й наименьший элемент дерева (1-индексация).\n\nПример:\nВход: tree=[3, 1, 4, None, 2], k=1\nInorder: [1, 2, 3, 4]\nВыход: 1",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bst-3",
    topicId: "derevya",
    subtopicId: "st-der-4",
    title: "BST в отсортированный список",
    description: "Дано BST в виде списка (level-order). Преобразуйте его в отсортированный список значений.\n\nПример:\nВход: [4, 2, 5, 1, 3]\nInorder обход BST даёт: [1, 2, 3, 4, 5]\nВыход: [1, 2, 3, 4, 5]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bal-1",
    topicId: "derevya",
    subtopicId: "st-der-5",
    title: "Проверка сбалансированности дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Определите, является ли оно сбалансированным по высоте — для каждого узла разница высот левого и правого поддеревьев не превышает 1.\n\nПример:\nВход: [3, 9, 20, None, None, 15, 7] → True\nВход: [1, 2, 2, 3, 3, None, None, 4, 4] → False",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-bal-2",
    topicId: "derevya",
    subtopicId: "st-der-5",
    title: "Диаметр бинарного дерева",
    description: "Дано бинарное дерево в виде списка (level-order). Найдите его диаметр — длину самого длинного пути между любыми двумя узлами (в рёбрах).\n\nПример:\nВход: [1, 2, 3, 4, 5]\nДерево:\n    1\n   / \\\n  2   3\n / \\\n4   5\nДиаметр: 4→2→1→3 = 3 ребра\nВыход: 3",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-seg-1",
    topicId: "derevya",
    subtopicId: "st-der-6",
    title: "Сумма на отрезке (префиксные суммы)",
    description: "Дан массив чисел и список запросов [l, r]. Для каждого запроса найдите сумму элементов от индекса l до r включительно.\n\nПример:\nВход: nums=[1, 3, 5, 7, 9], queries=[[0, 2], [1, 3]]\nВыход: [9, 15]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-seg-2",
    topicId: "derevya",
    subtopicId: "st-der-6",
    title: "Минимум на отрезке (дерево отрезков)",
    description: "Дан массив чисел и список запросов [l, r]. Для каждого запроса найдите минимальный элемент на отрезке от l до r включительно. Используйте дерево отрезков.\n\nПример:\nВход: nums=[1, 3, 2, 7, 9, 11], queries=[[0, 2], [1, 4]]\nВыход: [1, 2]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-seg-3",
    topicId: "derevya",
    subtopicId: "st-der-6",
    title: "Сумма на отрезке с обновлениями",
    description: "Дан массив чисел и список операций. Операция 'update' меняет значение по индексу, операция 'query' запрашивает сумму на отрезке [l, r]. Верните список результатов всех запросов.\n\nПример:\nВход: nums=[1, 3, 5], ops=[['query', 0, 2], ['update', 1, 10], ['query', 0, 2]]\nВыход: [9, 16]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-fen-1",
    topicId: "derevya",
    subtopicId: "st-der-7",
    title: "Префиксные суммы с обновлениями (дерево Фенвика)",
    description: "Дан массив чисел и список операций. Реализуйте поддержку точечных обновлений и запросов суммы на отрезке, используя дерево Фенвика (BIT).\n\nОперации: ['update', idx, val] — установить nums[idx] = val, ['query', l, r] — сумма на [l, r].\n\nПример:\nВход: nums=[1, 3, 5, 7], ops=[['query', 0, 2], ['update', 1, 10], ['query', 0, 2]]\nВыход: [9, 16]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "der-fen-2",
    topicId: "derevya",
    subtopicId: "st-der-7",
    title: "Подсчёт инверсий (дерево Фенвика)",
    description: "Дан массив целых чисел. Подсчитайте количество инверсий — пар (i, j), где i < j и nums[i] > nums[j].\n\nПример:\nВход: [2, 4, 1, 3, 5]\nИнверсии: (2,1), (4,1), (4,3) → 3\nВыход: 3",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-rep-1",
    topicId: "grafy",
    subtopicId: "st-graf-1",
    title: "Список рёбер в список смежности",
    description: "Дано количество вершин n и список рёбер неориентированного графа. Преобразуйте в список смежности (словарь). Соседей отсортируйте по возрастанию.\n\nПример:\nВход: n=3, edges=[(0,1), (0,2), (1,2)]\nВыход: {0: [1, 2], 1: [0, 2], 2: [0, 1]}",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-rep-2",
    topicId: "grafy",
    subtopicId: "st-graf-1",
    title: "Проверка двудольности графа",
    description: "Дан неориентированный граф (n вершин и список рёбер). Определите, является ли он двудольным — можно ли раскрасить вершины в два цвета так, чтобы никакие две смежные вершины не были одного цвета.\n\nПример:\nВход: n=4, edges=[(0,1),(1,2),(2,3),(3,0)] → True (цикл чётной длины)\nВход: n=3, edges=[(0,1),(1,2),(2,0)] → False (нечётный цикл)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-rep-3",
    topicId: "grafy",
    subtopicId: "st-graf-1",
    title: "Количество компонент связности",
    description: "Дан неориентированный граф (n вершин и список рёбер). Найдите количество компонент связности.\n\nПример:\nВход: n=5, edges=[(0,1),(1,2),(3,4)]\nКомпоненты: {0,1,2} и {3,4} → 2",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-bfs-1",
    topicId: "grafy",
    subtopicId: "st-graf-2",
    title: "Кратчайший путь в невзвешенном графе (BFS)",
    description: "Дан невзвешенный неориентированный граф и две вершины start и end. Найдите длину кратчайшего пути между ними. Если пути нет — верните -1.\n\nПример:\nВход: n=5, edges=[(0,1),(1,2),(2,3),(3,4)], start=0, end=4\nВыход: 4",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-bfs-2",
    topicId: "grafy",
    subtopicId: "st-graf-2",
    title: "Количество островов",
    description: "Дана сетка (двумерный массив) из 1 (земля) и 0 (вода). Остров — группа смежных (по 4 направлениям) клеток с 1. Найдите количество островов.\n\nПример:\nВход: [[1,1,0,0],[1,1,0,0],[0,0,1,0],[0,0,0,1]]\nВыход: 3",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-bfs-3",
    topicId: "grafy",
    subtopicId: "st-graf-2",
    title: "Цепочка слов (Word Ladder)",
    description: "Даны два слова beginWord и endWord, а также список слов wordList. Найдите длину кратчайшей цепочки преобразований от beginWord к endWord, где на каждом шаге меняется ровно одна буква, и каждое промежуточное слово есть в wordList. Если цепочки нет — верните 0.\n\nПример:\nВход: beginWord='hit', endWord='cog', wordList=['hot','dot','dog','lot','log','cog']\nЦепочка: hit → hot → dot → dog → cog (длина 5)\nВыход: 5",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-topo-1",
    topicId: "grafy",
    subtopicId: "st-graf-3",
    title: "Обнаружение цикла в ориентированном графе",
    description: "Дан ориентированный граф (n вершин и список рёбер). Определите, содержит ли он цикл.\n\nПример:\nВход: n=3, edges=[(0,1),(1,2),(2,0)] → True (цикл 0→1→2→0)\nВход: n=4, edges=[(0,1),(1,2),(2,3)] → False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-topo-2",
    topicId: "grafy",
    subtopicId: "st-graf-3",
    title: "Расписание курсов (можно ли пройти все?)",
    description: "Есть numCourses курсов (0..numCourses-1) и список пререквизитов [a, b] — чтобы пройти курс a, нужно сначала пройти b. Определите, можно ли пройти все курсы.\n\nПример:\nВход: numCourses=2, prerequisites=[(1,0)] → True (сначала 0, потом 1)\nВход: numCourses=2, prerequisites=[(1,0),(0,1)] → False (цикл)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-topo-3",
    topicId: "grafy",
    subtopicId: "st-graf-3",
    title: "Расписание курсов (порядок прохождения)",
    description: "Есть numCourses курсов и пререквизиты. Верните допустимый порядок прохождения всех курсов. Если невозможно — верните пустой список.\n\nПример:\nВход: numCourses=4, prerequisites=[(1,0),(2,0),(3,1),(3,2)]\nВыход: [0, 1, 2, 3] (или другой допустимый порядок)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-sp-1",
    topicId: "grafy",
    subtopicId: "st-graf-4",
    title: "Кратчайший путь в невзвешенном графе (восстановление пути)",
    description: "Дан невзвешенный неориентированный граф. Найдите и верните кратчайший путь от start до end в виде списка вершин. Если пути нет — верните пустой список.\n\nПример:\nВход: n=5, edges=[(0,1),(1,2),(2,3),(3,4)], start=0, end=4\nВыход: [0, 1, 2, 3, 4]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-sp-2",
    topicId: "grafy",
    subtopicId: "st-graf-4",
    title: "Алгоритм Дейкстры",
    description: "Дан взвешенный неориентированный граф (рёбра с неотрицательными весами). Найдите длину кратчайшего пути от start до end. Если пути нет — верните -1.\n\nПример:\nВход: n=4, edges=[(0,1,1),(1,2,2),(0,2,4),(2,3,1)], start=0, end=3\nПуть: 0→1→2→3 = 4\nВыход: 4",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-sp-3",
    topicId: "grafy",
    subtopicId: "st-graf-4",
    title: "Самый дешёвый перелёт с ограничением пересадок",
    description: "Есть n городов и список рейсов [from, to, price]. Найдите самый дешёвый маршрут из src в dst с не более чем k пересадками. Если маршрута нет — верните -1.\n\nПример:\nВход: n=3, flights=[(0,1,100),(1,2,100),(0,2,500)], src=0, dst=2, k=1\nМаршрут: 0→1→2 = 200 (1 пересадка)\nВыход: 200",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-mst-1",
    topicId: "grafy",
    subtopicId: "st-graf-5",
    title: "Минимальное остовное дерево (Краскал)",
    description: "Дан взвешенный неориентированный граф. Найдите вес минимального остовного дерева (MST) алгоритмом Краскала. Если граф несвязный — верните -1.\n\nПример:\nВход: n=4, edges=[(0,1,1),(0,2,2),(1,2,3),(1,3,4),(2,3,5)]\nMST рёбра: (0,1,1), (0,2,2), (1,3,4) → вес 7\nВыход: 7",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-mst-2",
    topicId: "grafy",
    subtopicId: "st-graf-5",
    title: "Минимальная стоимость соединения городов",
    description: "Есть n городов (0..n-1) и список возможных соединений [city1, city2, cost]. Найдите минимальную стоимость, чтобы соединить все города. Если невозможно — верните -1.\n\nПример:\nВход: n=4, connections=[(0,1,3),(1,2,1),(1,3,4),(2,3,2)]\nВыход: 6",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-cyc-1",
    topicId: "grafy",
    subtopicId: "st-graf-6",
    title: "Обнаружение цикла в неориентированном графе",
    description: "Дан неориентированный граф (n вершин и список рёбер). Определите, содержит ли он цикл.\n\nПример:\nВход: n=3, edges=[(0,1),(1,2),(2,0)] → True\nВход: n=4, edges=[(0,1),(1,2),(2,3)] → False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-cyc-2",
    topicId: "grafy",
    subtopicId: "st-graf-6",
    title: "Все вершины, входящие в циклы",
    description: "Дан ориентированный граф (n вершин и список рёбер). Найдите все вершины, которые являются частью какого-либо цикла. Верните их в отсортированном порядке.\n\nПример:\nВход: n=4, edges=[(0,1),(1,2),(2,0),(2,3)]\nЦикл: 0→1→2→0. Вершина 3 не в цикле.\nВыход: [0, 1, 2]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-cyc-3",
    topicId: "grafy",
    subtopicId: "st-graf-6",
    title: "Количество сильно связных компонент",
    description: "Дан ориентированный граф (n вершин и список рёбер). Найдите количество сильно связных компонент (SCC).\n\nSCC — максимальное подмножество вершин, где из каждой вершины можно добраться до любой другой.\n\nПример:\nВход: n=5, edges=[(0,1),(1,2),(2,0),(3,4)]\nSCC: {0,1,2}, {3}, {4} → 3",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-fw-1",
    topicId: "grafy",
    subtopicId: "st-graf-7",
    title: "Кратчайшие расстояния между всеми парами",
    description: "Дан взвешенный неориентированный граф. Найдите кратчайшие расстояния между всеми парами вершин (алгоритм Флойда-Уоршелла). Если пути нет — используйте -1.\n\nПример:\nВход: n=3, edges=[(0,1,1),(1,2,2),(0,2,4)]\nВыход: [[0, 1, 3], [1, 0, 2], [3, 2, 0]]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "graf-fw-2",
    topicId: "grafy",
    subtopicId: "st-graf-7",
    title: "Город с наименьшим числом достижимых соседей",
    description: "Дан взвешенный неориентированный граф из n городов. Найдите город, из которого достижимо наименьшее число других городов в пределах distanceThreshold. При одинаковом количестве выберите город с большим номером.\n\nПример:\nВход: n=4, edges=[(0,1,3),(1,2,1),(1,3,4),(2,3,1)], distanceThreshold=4\nГород 0: достижимы 1(3), 2(4) → 2 соседа\nГород 3: достижимы 1(2), 2(1) → 2 соседа\nВыход: 3 (тот же count, но номер больше)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-fibonacci",
    topicId: "dp",
    subtopicId: "st-dp-1",
    title: "Число Фибоначчи",
    description: "Дано целое неотрицательное число n. Верните n-е число Фибоначчи.\n\nПоследовательность Фибоначчи: F(0) = 0, F(1) = 1, F(n) = F(n-1) + F(n-2) для n > 1.\n\nПример:\nВход: n = 10\nВыход: 55\n\nПример:\nВход: n = 0\nВыход: 0",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-climbing-stairs",
    topicId: "dp",
    subtopicId: "st-dp-1",
    title: "Подъём по лестнице",
    description: "Вы поднимаетесь по лестнице из n ступеней. За один шаг можно подняться на 1 или 2 ступени. Сколько различных способов добраться до вершины?\n\nПример:\nВход: n = 3\nВыход: 3 (способы: 1+1+1, 1+2, 2+1)\n\nПример:\nВход: n = 5\nВыход: 8",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-unique-paths",
    topicId: "dp",
    subtopicId: "st-dp-1",
    title: "Уникальные пути в сетке",
    description: "Робот находится в левом верхнем углу сетки m × n. Он может двигаться только вправо или вниз. Сколько уникальных путей существует до правого нижнего угла?\n\nПример:\nВход: m = 3, n = 7\nВыход: 28\n\nПример:\nВход: m = 3, n = 2\nВыход: 3",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-min-path-sum",
    topicId: "dp",
    subtopicId: "st-dp-1",
    title: "Минимальная сумма пути в сетке",
    description: "Дана сетка m × n, заполненная неотрицательными числами. Найдите путь от левого верхнего до правого нижнего угла с минимальной суммой. Двигаться можно только вправо или вниз.\n\nПример:\nВход: [[1,3,1],[1,5,1],[4,2,1]]\nВыход: 7 (путь: 1→3→1→1→1)\n\nПример:\nВход: [[1,2,3],[4,5,6]]\nВыход: 12 (путь: 1→2→3→6)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-subset-sum",
    topicId: "dp",
    subtopicId: "st-dp-2",
    title: "Сумма подмножества",
    description: "Дан массив положительных целых чисел nums и целое число target. Определите, можно ли выбрать подмножество элементов массива так, чтобы их сумма равнялась target.\n\nПример:\nВход: nums = [3, 34, 4, 12, 5, 2], target = 9\nВыход: True (подмножество [4, 5] даёт сумму 9)\n\nПример:\nВход: nums = [3, 34, 4, 12, 5, 2], target = 30\nВыход: False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-knapsack-01",
    topicId: "dp",
    subtopicId: "st-dp-2",
    title: "Рюкзак 0/1",
    description: "Дано n предметов с весами weights и ценностями values, а также рюкзак вместимостью capacity. Каждый предмет можно взять или не взять (не более одного раза). Найдите максимальную суммарную ценность предметов, которые помещаются в рюкзак.\n\nПример:\nВход: weights = [2, 3, 4, 5], values = [3, 4, 5, 6], capacity = 5\nВыход: 7 (берём предметы с весами 2 и 3, ценности 3+4=7)\n\nПример:\nВход: weights = [1, 2, 3], values = [6, 10, 12], capacity = 5\nВыход: 22 (берём предметы с весами 2 и 3, ценности 10+12=22)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-coin-change",
    topicId: "dp",
    subtopicId: "st-dp-2",
    title: "Размен монет",
    description: "Дан массив номиналов монет coins и сумма amount. Верните минимальное количество монет, необходимое для набора этой суммы. Каждый номинал можно использовать неограниченное число раз. Если сумму набрать невозможно, верните -1.\n\nПример:\nВход: coins = [1, 2, 5], amount = 11\nВыход: 3 (5+5+1)\n\nПример:\nВход: coins = [2], amount = 3\nВыход: -1",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-range-sum-query",
    topicId: "dp",
    subtopicId: "st-dp-3",
    title: "Сумма на отрезке (префиксные суммы)",
    description: "Дан массив целых чисел nums и список запросов queries. Каждый запрос — пара [l, r]. Для каждого запроса верните сумму элементов от индекса l до r включительно.\n\nИспользуйте префиксные суммы для ответа на каждый запрос за O(1).\n\nПример:\nВход: nums = [1, 3, 5, 7, 9], queries = [[0, 2], [1, 3]]\nВыход: [9, 15]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-max-subarray",
    topicId: "dp",
    subtopicId: "st-dp-3",
    title: "Максимальная сумма подмассива",
    description: "Дан массив целых чисел nums. Найдите непрерывный подмассив с максимальной суммой и верните эту сумму (алгоритм Кадане).\n\nПример:\nВход: nums = [-2, 1, -3, 4, -1, 2, 1, -5, 4]\nВыход: 6 (подмассив [4, -1, 2, 1])\n\nПример:\nВход: nums = [-1, -2, -3]\nВыход: -1",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-lis",
    topicId: "dp",
    subtopicId: "st-dp-3",
    title: "Наибольшая возрастающая подпоследовательность",
    description: "Дан массив целых чисел nums. Найдите длину наибольшей строго возрастающей подпоследовательности (LIS).\n\nПример:\nВход: nums = [10, 9, 2, 5, 3, 7, 101, 18]\nВыход: 4 (например, [2, 3, 7, 18])\n\nПример:\nВход: nums = [0, 1, 0, 3, 2, 3]\nВыход: 4 (например, [0, 1, 2, 3])",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-count-subsets",
    topicId: "dp",
    subtopicId: "st-dp-4",
    title: "Подсчёт подмножеств (битмаски)",
    description: "Дан массив целых чисел nums из n элементов. Используя перебор по битовым маскам, подсчитайте общее количество подмножеств массива (включая пустое подмножество).\n\nДля массива из n элементов битовая маска — число от 0 до 2^n - 1, где каждый бит указывает, включён ли соответствующий элемент.\n\nПример:\nВход: nums = [1, 2, 3]\nВыход: 8 (подмножества: {}, {1}, {2}, {3}, {1,2}, {1,3}, {2,3}, {1,2,3})",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-partition-equal-subset",
    topicId: "dp",
    subtopicId: "st-dp-4",
    title: "Разбиение на два равных подмножества",
    description: "Дан массив положительных целых чисел nums. Определите, можно ли разбить его на два подмножества с одинаковой суммой.\n\nПример:\nВход: nums = [1, 5, 11, 5]\nВыход: True (подмножества [1, 5, 5] и [11], суммы по 11)\n\nПример:\nВход: nums = [1, 2, 3, 5]\nВыход: False (общая сумма 11 — нечётная)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-tsp-bitmask",
    topicId: "dp",
    subtopicId: "st-dp-4",
    title: "Задача коммивояжёра (Bitmask DP)",
    description: "Дана матрица расстояний dist размером n × n, где dist[i][j] — стоимость перехода из города i в город j. Найдите минимальную стоимость маршрута, который начинается в городе 0, посещает все города ровно один раз и возвращается в город 0.\n\nПример:\nВход: [[0, 1, 2], [1, 0, 3], [2, 3, 0]]\nВыход: 6 (маршрут: 0→1→2→0, стоимость 1+3+2=6)\n\nПример:\nВход: [[0, 10, 15, 20], [10, 0, 35, 25], [15, 35, 0, 30], [20, 25, 30, 0]]\nВыход: 80",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-house-robber",
    topicId: "dp",
    subtopicId: "st-dp-5",
    title: "Ограбление домов",
    description: "Вы — грабитель, планирующий ограбить дома вдоль улицы. В каждом доме спрятана определённая сумма денег. Нельзя грабить два соседних дома подряд (сработает сигнализация). Найдите максимальную сумму, которую можно украсть.\n\nПример:\nВход: nums = [1, 2, 3, 1]\nВыход: 4 (ограбить дома 0 и 2: 1+3=4)\n\nПример:\nВход: nums = [2, 7, 9, 3, 1]\nВыход: 12 (ограбить дома 0, 2, 4: 2+9+1=12)",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-longest-path-dag",
    topicId: "dp",
    subtopicId: "st-dp-5",
    title: "Наидлиннейший путь в DAG",
    description: "Дан ориентированный ациклический граф (DAG) с n вершинами (от 0 до n-1) и список рёбер. Найдите длину наидлиннейшего пути в графе (количество рёбер).\n\nПример:\nВход: n = 5, edges = [[0,1],[0,2],[1,3],[2,3],[3,4]]\nВыход: 3 (путь: 0→1→3→4 или 0→2→3→4)\n\nПример:\nВход: n = 4, edges = [[0,1],[1,2],[2,3]]\nВыход: 3",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "dp-max-independent-set-tree",
    topicId: "dp",
    subtopicId: "st-dp-5",
    title: "Максимальное независимое множество на дереве",
    description: "Дано дерево из n вершин (от 0 до n-1) со списком рёбер и массивом весов вершин. Найдите максимальную сумму весов независимого множества — такого набора вершин, в котором никакие две не соединены ребром.\n\nПример:\nВход: n = 5, edges = [[0,1],[0,2],[1,3],[1,4]], weights = [1, 5, 3, 2, 4]\nВыход: 9 (выбираем вершины 2, 3, 4: веса 3+2+4=9)\n\nПример:\nВход: n = 3, edges = [[0,1],[1,2]], weights = [5, 1, 5]\nВыход: 10 (вершины 0 и 2: 5+5=10)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-kth-largest-heap",
    topicId: "struktury",
    subtopicId: "st-str-1",
    title: "K-й наибольший элемент",
    description: "Дан массив целых чисел nums и число k. Найдите k-й наибольший элемент в массиве, используя кучу (heap).\n\nПример:\nВход: nums = [3, 2, 1, 5, 6, 4], k = 2\nВыход: 5\n\nПример:\nВход: nums = [3, 2, 3, 1, 2, 4, 5, 5, 6], k = 4\nВыход: 4",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-merge-k-sorted-lists",
    topicId: "struktury",
    subtopicId: "st-str-1",
    title: "Слияние k отсортированных списков",
    description: "Дан массив из k отсортированных (по возрастанию) списков целых чисел. Объедините их в один отсортированный список, используя кучу (приоритетную очередь).\n\nПример:\nВход: [[1, 4, 7], [2, 5, 8], [3, 6, 9]]\nВыход: [1, 2, 3, 4, 5, 6, 7, 8, 9]\n\nПример:\nВход: [[1, 3, 5], [2, 4, 6]]\nВыход: [1, 2, 3, 4, 5, 6]",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-running-median",
    topicId: "struktury",
    subtopicId: "st-str-1",
    title: "Медиана потока чисел",
    description: "Дан массив чисел nums. Для каждого элемента вычислите медиану всех элементов, считанных до этого момента (включительно). Верните список медиан.\n\nМедиана — среднее значение для чётного количества элементов, и средний элемент для нечётного.\n\nПример:\nВход: [1, 2, 3]\nВыход: [1, 1.5, 2]\n\nПример:\nВход: [5, 2, 8, 1]\nВыход: [5, 3.5, 5, 3.5]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-deque-simulation",
    topicId: "struktury",
    subtopicId: "st-str-2",
    title: "Симуляция двусторонней очереди",
    description: "Реализуйте симуляцию операций двусторонней очереди (deque). Дан список команд, где каждая команда — список: [код_операции, ...аргументы].\n\nКоды операций:\n1 val — push_front (добавить val в начало)\n2 val — push_back (добавить val в конец)\n3 — pop_front (удалить и вернуть из начала, или -1 если пусто)\n4 — pop_back (удалить и вернуть из конца, или -1 если пусто)\n5 — front (вернуть первый элемент, или -1 если пусто)\n6 — back (вернуть последний элемент, или -1 если пусто)\n7 — size (вернуть размер)\n\nВерните массив результатов операций, возвращающих значения (3-7).\n\nПример:\nВход: [[2,1],[2,2],[1,3],[5],[6],[3],[4],[7]]\nВыход: [3, 2, 3, 2, 1]",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-sliding-window-max",
    topicId: "struktury",
    subtopicId: "st-str-2",
    title: "Максимум скользящего окна",
    description: "Дан массив целых чисел nums и размер окна k. Окно сдвигается слева направо на одну позицию за шаг. Верните максимум в каждом положении окна.\n\nПример:\nВход: nums = [1, 3, -1, -3, 5, 3, 6, 7], k = 3\nВыход: [3, 3, 5, 5, 6, 7]\n\nОбъяснение:\nОкно [1,3,-1] → max=3, [3,-1,-3] → max=3, [-1,-3,5] → max=5, ...",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-shortest-subarray-sum",
    topicId: "struktury",
    subtopicId: "st-str-2",
    title: "Кратчайший подмассив с суммой ≥ k",
    description: "Дан массив целых чисел nums (могут быть отрицательные) и число k. Найдите длину кратчайшего непрерывного подмассива, сумма которого не менее k. Если такого подмассива нет, верните -1.\n\nПример:\nВход: nums = [2, -1, 2], k = 3\nВыход: 3\n\nПример:\nВход: nums = [1, 2], k = 4\nВыход: -1",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-word-search-trie",
    topicId: "struktury",
    subtopicId: "st-str-3",
    title: "Поиск слова (Trie)",
    description: "Дан список слов words и слово word. Проверьте, существует ли word в списке words, используя структуру данных Trie (префиксное дерево).\n\nПример:\nВход: words = [\"apple\", \"app\", \"application\"], word = \"app\"\nВыход: True\n\nПример:\nВход: words = [\"apple\", \"app\"], word = \"ap\"\nВыход: False",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-count-words-prefix",
    topicId: "struktury",
    subtopicId: "st-str-3",
    title: "Подсчёт слов с заданным префиксом",
    description: "Дан список слов words и строка prefix. Подсчитайте, сколько слов из списка начинаются с данного префикса.\n\nПример:\nВход: words = [\"apple\", \"app\", \"application\", \"banana\", \"band\"], prefix = \"app\"\nВыход: 3 (apple, app, application)\n\nПример:\nВход: words = [\"hello\", \"help\", \"hero\", \"her\"], prefix = \"her\"\nВыход: 2 (hero, her)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-longest-common-prefix",
    topicId: "struktury",
    subtopicId: "st-str-3",
    title: "Наидлиннейший общий префикс",
    description: "Дан массив строк strs. Найдите наидлиннейший общий префикс среди всех строк. Если общего префикса нет, верните пустую строку.\n\nПример:\nВход: [\"flower\", \"flow\", \"flight\"]\nВыход: \"fl\"\n\nПример:\nВход: [\"dog\", \"racecar\", \"car\"]\nВыход: \"\"",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-count-components-uf",
    topicId: "struktury",
    subtopicId: "st-str-4",
    title: "Количество компонент связности (Union-Find)",
    description: "Дан неориентированный граф с n вершинами (от 0 до n-1) и список рёбер. Используя структуру Union-Find, найдите количество компонент связности.\n\nПример:\nВход: n = 5, edges = [[0,1],[1,2],[3,4]]\nВыход: 2 (компоненты: {0,1,2} и {3,4})\n\nПример:\nВход: n = 4, edges = [[0,1],[1,2],[2,3]]\nВыход: 1",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-detect-cycle-uf",
    topicId: "struktury",
    subtopicId: "st-str-4",
    title: "Обнаружение цикла (Union-Find)",
    description: "Дан неориентированный граф с n вершинами и список рёбер. Используя Union-Find, определите, содержит ли граф цикл.\n\nПример:\nВход: n = 4, edges = [[0,1],[1,2],[2,0]]\nВыход: True (ребро 2→0 замыкает цикл)\n\nПример:\nВход: n = 3, edges = [[0,1],[1,2]]\nВыход: False",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "str-components-after-removal",
    topicId: "struktury",
    subtopicId: "st-str-4",
    title: "Компоненты связности после удаления рёбер",
    description: "Дан неориентированный граф с n вершинами и список рёбер edges (индексированных с 0). Дан массив removals — последовательность индексов рёбер для удаления. После каждого удаления (кумулятивно) подсчитайте количество компонент связности.\n\nПример:\nВход: n = 5, edges = [[0,1],[1,2],[2,3],[3,4],[0,4]], removals = [4, 2]\nВыход: [1, 2]\nПояснение: удалили ребро 4 (0-4) → 1 компонента; затем ребро 2 (2-3) → 2 компоненты.\n\nПример:\nВход: n = 3, edges = [[0,1],[1,2],[0,2]], removals = [0, 1, 2]\nВыход: [1, 2, 3]",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-pattern-search",
    topicId: "prodvinutye",
    subtopicId: "st-prod-1",
    title: "Поиск подстроки в тексте",
    description: "Даны строки text и pattern. Найдите индекс первого вхождения pattern в text. Если pattern не найден, верните -1.\n\nПример:\nВход: text = \"hello world\", pattern = \"world\"\nВыход: 6\n\nПример:\nВход: text = \"abcdef\", pattern = \"xyz\"\nВыход: -1",
    difficulty: "easy",
    points: 10,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-count-pattern-occurrences",
    topicId: "prodvinutye",
    subtopicId: "st-prod-1",
    title: "Количество вхождений подстроки",
    description: "Даны строки text и pattern. Подсчитайте количество всех вхождений pattern в text (включая перекрывающиеся).\n\nПример:\nВход: text = \"ababab\", pattern = \"ab\"\nВыход: 3 (позиции 0, 2, 4)\n\nПример:\nВход: text = \"aaaa\", pattern = \"aa\"\nВыход: 3 (позиции 0, 1, 2 — перекрывающиеся)",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-shortest-palindrome",
    topicId: "prodvinutye",
    subtopicId: "st-prod-1",
    title: "Кратчайший палиндром",
    description: "Дана строка s. Добавьте минимальное количество символов в начало строки, чтобы сделать её палиндромом. Верните результат.\n\nАлгоритм основан на KMP: найдите наидлиннейший палиндромный префикс строки.\n\nПример:\nВход: s = \"aacecaaa\"\nВыход: \"aaacecaaa\"\n\nПример:\nВход: s = \"abcd\"\nВыход: \"dcbabcd\"",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-range-sum-sqrt",
    topicId: "prodvinutye",
    subtopicId: "st-prod-2",
    title: "Сумма на отрезке (sqrt-декомпозиция)",
    description: "Дан массив целых чисел nums и список запросов queries. Каждый запрос — список:\n- [0, l, r] — вернуть сумму элементов от l до r включительно\n- [1, idx, val] — обновить nums[idx] = val\n\nРеализуйте решение с использованием sqrt-декомпозиции.\n\nПример:\nВход: nums = [1, 3, 5, 7, 9, 11], queries = [[0, 1, 3], [1, 2, 10], [0, 1, 3]]\nВыход: [15, 20]\nПояснение: сумма [1..3]=3+5+7=15; обновляем nums[2]=10; сумма [1..3]=3+10+7=20",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-range-min-sqrt",
    topicId: "prodvinutye",
    subtopicId: "st-prod-2",
    title: "Минимум на отрезке (sqrt-декомпозиция)",
    description: "Дан массив целых чисел nums и список запросов queries. Каждый запрос:\n- [0, l, r] — вернуть минимум на отрезке [l, r]\n- [1, idx, val] — обновить nums[idx] = val\n\nРеализуйте решение с использованием блочной (sqrt) декомпозиции.\n\nПример:\nВход: nums = [2, 4, 1, 5, 3, 7], queries = [[0, 0, 3], [1, 2, 6], [0, 0, 3]]\nВыход: [1, 2]\nПояснение: min [0..3]=min(2,4,1,5)=1; обновляем nums[2]=6; min [0..3]=min(2,4,6,5)=2",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-bipartite-matching",
    topicId: "prodvinutye",
    subtopicId: "st-prod-3",
    title: "Максимальное паросочетание в двудольном графе",
    description: "Дан двудольный граф: n вершин слева (0..n-1), m вершин справа (0..m-1) и список рёбер (каждое ребро соединяет левую и правую вершину). Найдите размер максимального паросочетания.\n\nПример:\nВход: n = 3, m = 3, edges = [[0,0],[0,1],[1,0],[2,1]]\nВыход: 2\n\nПример:\nВход: n = 2, m = 2, edges = [[0,0],[0,1],[1,0],[1,1]]\nВыход: 2",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-max-flow",
    topicId: "prodvinutye",
    subtopicId: "st-prod-3",
    title: "Максимальный поток в сети",
    description: "Дана сеть из n вершин (0..n-1), список рёбер с пропускными способностями [u, v, capacity], исток source и сток sink. Найдите максимальный поток от source к sink (алгоритм Эдмондса-Карпа / BFS-версия Форда-Фалкерсона).\n\nПример:\nВход: n = 4, edges = [[0,1,10],[0,2,10],[1,3,10],[2,3,10]], source = 0, sink = 3\nВыход: 20\n\nПример:\nВход: n = 2, edges = [[0,1,5]], source = 0, sink = 1\nВыход: 5",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-matrix-fibonacci",
    topicId: "prodvinutye",
    subtopicId: "st-prod-4",
    title: "Числа Фибоначчи через возведение матрицы в степень",
    description: "Вычислите n-е число Фибоначчи, используя быстрое возведение матрицы в степень.\n\nМатричное тождество: [[1,1],[1,0]]^n = [[F(n+1),F(n)],[F(n),F(n-1)]]\n\nЭтот метод работает за O(log n) вместо O(n).\n\nПример:\nВход: n = 10\nВыход: 55\n\nПример:\nВход: n = 50\nВыход: 12586269025",
    difficulty: "medium",
    points: 20,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  },
  {
    id: "prod-count-paths-matrix",
    topicId: "prodvinutye",
    subtopicId: "st-prod-4",
    title: "Количество путей длины k в графе (матричное возведение)",
    description: "Дана матрица смежности adj ориентированного графа (adj[i][j] = 1, если есть ребро i→j, иначе 0). Даны число k и вершины u, v. Найдите количество путей длины ровно k из u в v.\n\nОтвет — элемент [u][v] матрицы adj^k.\n\nПример:\nВход: adj = [[0,1,1],[0,0,1],[1,0,0]], k = 2, u = 0, v = 2\nВыход: 1 (путь: 0→1→2)\n\nПример:\nВход: adj = [[0,1,0],[0,0,1],[1,0,0]], k = 3, u = 0, v = 0\nВыход: 1 (путь: 0→1→2→0)",
    difficulty: "hard",
    points: 30,
    expectedOutput: '',
    hints: [],
    solutionTemplate: '',
    testCases: [],
  }
];

export const THEORIES: Record<string, string> = {
  'theory-osnovy': '# Основы\n\nБазовые концепции алгоритмов и структур данных.',
  'theory-rekursiya': '# Рекурсия\n\nРекурсивные алгоритмы и техники.',
  'theory-sortirovki': '# Сортировки\n\nОсновные алгоритмы сортировки.',
  'theory-poisk': '# Поиск\n\nАлгоритмы поиска.',
  'theory-derevya': '# Деревья\n\nДревовидные структуры данных.',
  'theory-grafy': '# Графы\n\nАлгоритмы на графах.',
  'theory-dp': '# Динамическое программирование\n\nОптимизация через подзадачи.',
  'theory-struktury': '# Структуры данных\n\nДополнительные структуры.',
  'theory-prodvinutye': '# Продвинутые темы\n\nПродвинутые алгоритмы.',
};

/** Ordered list of task IDs for prev/next navigation (follows roadmap structure) */
export function getOrderedTaskIds(): string[] {
  const ids: string[] = [];
  for (const topic of ROADMAP) {
    for (const subtopic of topic.subtopics) {
      const stTasks = TASKS.filter((t) => t.topicId === topic.id && t.subtopicId === subtopic.id);
      ids.push(...stTasks.map((t) => t.id));
    }
    const topicTasks = TASKS.filter((t) => t.topicId === topic.id && !t.subtopicId);
    ids.push(...topicTasks.map((t) => t.id));
  }
  return ids;
}

/** Flat list of topics + subtopics with taskIds (e.g. for animation page) */
export const ROADMAP_TOPICS = ROADMAP.flatMap((t) => [
  { id: t.id, title: t.title, theory: `theory-${t.id}` as const, taskIds: TASKS.filter((x) => x.topicId === t.id).map((x) => x.id) },
  ...t.subtopics.map((s) => ({
    id: s.id,
    title: s.title,
    theory: undefined as string | undefined,
    taskIds: TASKS.filter((x) => x.topicId === t.id && x.subtopicId === s.id).map((x) => x.id),
  })),
]);
